version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "
      python wait_for_db.py &&
      granian --interface asgi --host 0.0.0.0 --port 8000 app:asgi_app
      "
    volumes:
      - ./static:/backend_static
      - ./media:/backend_media

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always

volumes:
  postgres_data:
